### ISSUE TITLE
React Widget with BrowserRouter inside Drupal

### ISSUE THREAD

**Issue by savkelita** [pianomansam/drupal-react-widget-module#1]
Hi @pianomansam, I saw your [post](https://www.rapiddg.com/article/how-add-react-widget-drupal-8-site) about integration React application inside Drupal, thank you great Article. Based on it my question is below:

I have a `Drupal 10` site with one page at the following URL: `localhost:9090/my-page`. On that page, I have a `Drupal block` that includes a `React app` with its own `Browser Router`.

React **BrowserRouter** configuration:

```
<BrowserRouter basename="/my-page">
  <App />
</BrowserRouter>
```

React **Routes**:

```
<Routes>
  <Route index path="/demo-1" element={<DemoOne />} />
  <Route path="/demo-2" element={<DemoTwo />} />
</Routes>
```

When I access the `My Page`, the `React App` shows up, and I can use `React Router` normally, and the URL changes. The problem occurs when I reload the page; **Drupal gives me a 404 error**.

Example: [**localhost:9090/my-page/demo-1**](http://www.demo.com/my-page/demo-1)

I'm using `Nginx`, and perhaps I need some extra configuration for this scenario.

**This is an example what I exactly need:**

https://iap.unido.org/data/sdg-9-industry?p=LBY

Base is `/data` and `/data/sdg-9-industry` is some page inside **React App**.

Any help or idea is much appreciated! Thanks!

**Comment by pianomansam** [comment]
@savkelita you won't be able to use <BrowserRouter> with the Drupal frontend because Drupal's router receives the request first. You'll need to use a different React router, such as a hash router.

**Comment by savkelita** [comment]
@pianomansam Thank you for answer i plan to use a hash router as solution, but still can't reconize how they implement it with browser router... Did you check example above? Thanks

**Comment by pianomansam** [comment]
@savkelita looking at that example, it appears that `/data/sdg-9-industry` is the page within Drupal. If you inside `<script type="application/json" data-drupal-selector="drupal-settings-json">` you will see that the `currentPath` is `data/sdg-9-industry`. When you interact with the select boxes at the top of the page, the query parameters change. But the path stays the same.

**Comment by savkelita** [comment]
@pianomansam Hi it looks like that's the solution. I'm gonna try to create a sub-page without any content just to avoid 404 and I hope then I'll get react app. Thank you very much! I'll give you a feedback.

**Comment by savkelita** [comment]
@pianomansam Mate it works! Solution is really crazy. :D 

I have base page `/my-page`. Then I add another page `demo-1` and custom url for it `/data/demo-1`. What is important to have is react widget on every page. Of course, hash router is the best solution but i need clean URL-s. 

Thank you very much for hint and help! Have a nice day, Marko. 🍾
